version: "3.8"
services:
  task:
    dockerfile: Dockerfile
    entrypoint: ["/entrypoint.sh"]
    env_file: ".env.compose"
    mounts:
      - type: bind
        source: ../.. # Bind mount the entire repo
        target: /app
    ports:
      - "4096"
