version: "3.8"
services:
  task:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/entrypoint.sh"]
    env_file: ".env.compose"
    volumes:
      - type: bind
        source: ../.. # Bind mount the entire repo
        target: /app
    ports:
      - "4096"
